name: python3.8.7 static build and check

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  macos_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: fetch python release
        run: wget https://github.com/RapidSilicon/post_build_artifacts/releases/download/v0.1/python3.8_static_lib.tar.gz
      - name: extract and test
        run: |
            tar -xvzf python3.8_static_lib.tar.gz
            cd python3.8/bin
            ./python3.8 -V
        
