name: python3.8.7 static build and check

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  macos_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: brew install wget
